### ISSUE TITLE
`Error: Cannot find package 'fs'` when run under node.js v12

### ISSUE THREAD

**Issue by cpcallen** [ChadKillingsworth/closure-calculate-chunks#5]
When run under node.js v12 (which is still in LTS), `closure-calculate-chunks` fails with the following error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fs' imported from […]/node_modules/closure-calculate-chunks/lib/chunk-graph.js
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

This is obviously inconvenient for those of us who use it as part of our build pipeline, and who test building on older versions of node.js.

**Comment by ChadKillingsworth** [comment]
This package uses native ES Modules with node and only supports Node 14+. That was by design.

I realize this causes an inconvenience for some, but Node 12 is end of live in 7 months. I wanted to use the latest functionality.

**Comment by ChadKillingsworth** [comment]
This is indicated by the node version specified in the package.json: https://github.com/ChadKillingsworth/closure-calculate-chunks/blob/main/package.json#L24
